
[oregen]
	#Decide if you want Tutorial Mod ores to spawn in the overworld
	generate_overworld = true
	#Maximum number of ore veins of the tutorial ore that can spawn in one chunk.
	#Range: 1 ~ 1000000
	tutorial_chance = 20

